version: "3.7"
services:
    wildduck:
        restart: always
        image: nodemailer/wildduck
        ports:
            - "8080:8080"
            - "143:143"
            - "110:110"
            - "993:993"
            - "995:995"
        depends_on:
            - redis
            - mongo
        environment:
            CMD_ARGS: 
                --dbs.mongo=mongodb://mongo:27017/wildduck
                --dbs.redis=redis://redis:6379/3
                --api.host=0.0.0.0
                --api.accessToken=PLEASE_CHANGE_ME
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - /data
    mongo:
        image: mongo
        restart: always
        volumes:
            - /data/db